// LemonAid Tagline Variety - Fresh alternatives to avoid overuse

export const taglines = {
  // Primary tagline (classic)
  primary: "When code throws you lemons, you get LemonAid",
  
  // Hero variations
  hero: [
    "Turn Sour Code Into Sweet Success",
    "Squeeze Out Perfect Code, Every Time",
    "From Bitter Bugs to Sweet Solutions",
    "Fresh Code, Freshly Squeezed",
    "Making Lemonade Out of Legacy Code",
  ],
  
  // Short & punchy
  short: [
    "Code Made Sweet",
    "Freshly Squeezed Code",
    "Sweet Code, Guaranteed",
    "No More Sour Code",
    "Zest for Perfect Code",
  ],
  
  // Playful variations
  playful: [
    "Life Gives You Bugs? We Give You Features",
    "Coding Never Tasted This Good",
    "Your Daily Dose of Vitamin Code",
    "Refreshingly Simple Development",
    "Add Some Zest to Your Tech Stack",
  ],
  
  // Professional variations  
  professional: [
    "Professional Websites, Web Apps, and HTML5 Games Generated by AI",
    "AI-Powered Development, Delivered Fresh",
    "Build Better, Ship Faster, Code Sweeter",
    "Enterprise-Grade AI Development Platform",
    "Where AI Meets Artisan Code",
  ],
  
  // Footer variations
  footer: [
    "Squeezing the Best Out of AI",
    "Fresh Code Daily Since 2025",
    "Your AI Coding Companion",
    "Making Development Deliciously Simple",
    "Code. Squeezed. Perfected.",
  ],
  
  // CTA variations
  cta: [
    "Start Squeezing Out Amazing Projects",
    "Get Your Fresh Code Fix",
    "Taste the Difference AI Makes",
    "Build Something Refreshing",
    "Experience Code That's Good For You",
  ],
};

// Get a random tagline from a category
export function getRandomTagline(category: keyof typeof taglines = 'hero'): string {
  const options = taglines[category];
  if (Array.isArray(options)) {
    return options[Math.floor(Math.random() * options.length)];
  }
  return options as string;
}

// Get a different tagline than the one provided
export function getAlternateTagline(current: string, category: keyof typeof taglines = 'hero'): string {
  const options = taglines[category];
  if (!Array.isArray(options)) return current;
  
  const filtered = options.filter(t => t !== current);
  return filtered[Math.floor(Math.random() * filtered.length)] || options[0];
}
